### ISSUE TITLE
Ping LAN 

### ISSUE THREAD

**Issue by hcurtiss** [ich777/docker-openvpn-client#11]
When connected to VPN, I can ping external servers, but I cannot ping other devices on the LAN from console. Is there some flag to enable this?  Thought maybe I could set a variable for LAN_NETWORK (192.168.1.0/24), but didn't work.  Thoughts?

**Comment by ich777** [comment]
Please look at this post: [Click](https://forums.unraid.net/topic/83786-support-ich777-application-dockers/?do=findComment&comment=1301879)

I also don't know nothing about your setup with that little information given.

**Comment by heathcurtiss** [comment]
Wow.  That totally did it.  Thank you! For those looking for this, use ROUTE instead of LAN_NETWORK.

**Comment by ich777** [comment]
@hcurtiss exactly as the readme says. ;)
