### ISSUE TITLE
vpn connection does not restart after down

### ISSUE THREAD

**Issue by ron06g** [ich777/docker-openvpn-client#16]
Hello,
At start, the vpn connexion Up, but after a moment, the connection is not able to up again.

```
2024-11-12 16:51:37 AEAD Decrypt error: bad packet ID (may be a replay): [ #4720141 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Error: ipv4: FIB table does not exist.
Dump terminated
+ exec sg vpn -c 'openvpn --cd /vpn --config /vpn/vpn.ovpn --script-security 2 --redirect-gateway def1 --route-up '\''/bin/sh -c " iptables -A OUTPUT -d 127.0.0.11 -j ACCEPT"'\'' --route-pre-down '\''/bin/sh -c " iptables -D OUTPUT -d 127.0.0.11 -j ACCEPT"'\'' --auth-user-pass /vpn/vpn.auth                 '
2024-11-12 16:51:48 AEAD Decrypt error: bad packet ID (may be a replay): [ #4742231 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
2024-11-12 16:52:16 AEAD Decrypt error: bad packet ID (may be a replay): [ #4796218 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
2024-11-12 16:52:16 AEAD Decrypt error: bad packet ID (may be a replay): [ #4796221 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
```

**Comment by ich777** [comment]
> At start, the vpn connexion Up, but after a moment, the connection is not able to up again.

Can you give me your `docker run` command from the container please?
It would be really helpful which variables that you are using.

**Comment by ron06g** [comment]
it was launch from unraid system

```
docker run
  -d
  --name='OpenVPN-Client'
  --net='lan_vpn'
  --pids-limit 2048
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="UNRAID"
  -e HOST_CONTAINERNAME="OpenVPN-Client"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/ich777/docker-templates/master/ich777/images/openvpn-client.png'
  -p '9091:9091/tcp'
  -p '51413:51413/tcp'
  -v '/mnt/user/appdata/openvpn-client/':'/vpn':'rw'
  --device='/dev/net/tun'
  --cap-add=NET_ADMIN
  --dns=1.1.1.1 'ich777/openvpn-client'
  -f''
```

**Comment by ich777** [comment]
@ron06g you can try to add these variables to your Docker template:
![grafik](https://github.com/user-attachments/assets/76c6e1af-2142-4202-9dc2-667f22ad59ff)

and maybe that one for the interval:
![grafik](https://github.com/user-attachments/assets/ebb75f98-77cc-44ea-bf8f-67f926071ab0)

(you don't have to add the second variable because by default the interval is set to 30 seconds but that is a bit strict in my opinion)

With that the container will restart entirely, do keep in mind if that happens all containers who are using this network need to be restarted too, the container has [this feature](https://github.com/ich777/docker-openvpn-client?tab=readme-ov-file#starting-an-openvpn-client-instance-with-ping-and-connected-containers) built into to restart connected containers if they support it.

**Comment by ron06g** [comment]
Thank you, i try that.
Your project is very usefull, Good job

**Comment by ron06g** [comment]
I always have the error

<img width="1203" alt="Capture d’écran 2024-11-14 à 13 53 37" src="https://github.com/user-attachments/assets/09224ac2-a134-46d3-bfc4-64a69e74195b">

**Comment by ich777** [comment]
> I always have the error

The error that you are experiencing comes from your VPN or maybe a bad configuration, what VPN provider do you use?
I have no issue at all with PIA, the connection is even reestablished if it drops and I didn't even have to use the variable `PING_IP`.

The container will only restart if you are using `--restart=unless-stopped` in the Extra Parameters from the template, did you remove that since it's the default in the template...

**Comment by ich777** [comment]
Any update on this?

**Comment by ron06g** [comment]
Hello,
I think that i have solved the probleme -> 36 hours without error !
I have added the line "pull-filter ignore redirect-gateway" at the end of my ".ovpn" config file.

Thank you for your help !

**Comment by Crylia** [comment]
Hi, I have the same issue but I use ProtonVPN and `adding pull-filter ignore redirect-gateway` didnt work for me.

I noticed it only happens when I start the dockers too, for example qbittorrent instantly triggers it while others take a while.

```
docker run
  -d
  --name='OpenVPN-Client'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Bocchi"
  -e HOST_CONTAINERNAME="OpenVPN-Client"
  -e 'FIREWALL'=''
  -e 'CONNECTED_CONTAINERS'=''
  -e 'PING_IP'='1.1.1.1'
  -e 'PING_INTERVAL'='30'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/ich777/docker-templates/master/ich777/images/openvpn-client.png'
  -p '8686:8686/tcp'
  -p '8989:8989/tcp'
  -p '7878:7878/tcp'
  -p '8082:8082/udp'
  -p '8096:8096/tcp'
  -p '8080:8080/tcp'
  -p '5055:5055/tcp'
  -p '17442:17442/tcp'
  -p '8054:8054/tcp'
  -p '6881:6881/tcp'
  -p '6881:6881/udp'
  -p '5000:5000/tcp'
  -v '/mnt/cache/appdata/openvpn-client':'/vpn':'rw'
  --device='/dev/net/tun'
  --cap-add=NET_ADMIN
  --dns=1.1.1.1
  --restart=unless-stopped 'ich777/openvpn-client' 
  ```

**Comment by ich777** [comment]
> I noticed it only happens when I start the dockers too, for example qbittorrent instantly triggers it while others take a while.

Can you please be a bit more specific what you mean with that?

Please also attach the logs from your container.

If you get the same message as the user from above this is most likely a configuration issue on the Server side, so to speak from your VPN Provider.
I only have PIA and it is working flawlessly.

**Comment by Crylia** [comment]
> > I noticed it only happens when I start the dockers too, for example qbittorrent instantly triggers it while others take a while.
> 
> Can you please be a bit more specific what you mean with that?
> 
> Please also attach the logs from your container.
> 
> If you get the same message as the user from above this is most likely a configuration issue on the Server side, so to speak from your VPN Provider. I only have PIA and it is working flawlessly.

I get exactly the same message as above, I have no problems with the config on my PC, there is nothing else in the logs. It also looks like it works for half a minute, then doesnt for half a minute, its really weird.

**Comment by ich777** [comment]
> I have no problems with the config on my PC

What App are you using on your PC?
If you are using OpenVPN is it the same version, what operating system are you using on your PC?


> It also looks like it works for half a minute, then doesnt for half a minute, its really weird.

As said above, I never experienced this message, however it seems that this is only a warning and can be maybe safely be ignored...?

AFAIK AEAD errors are cause by packet loss, time differences between the server and client, a configuration issue or a network issue in general.
