### ISSUE TITLE
DNS option fails

### ISSUE THREAD

**Issue by brianramseyau** [ich777/docker-openvpn-client#3]
Hello,

First of all thanks for picking up the ongoing maintenance on this container, it's great to be able to keep using it.

While porting over my config from the dperson container, I found my config did not work "drop-in".

Due to some issues previously (old container) I had set the DNS environment variable to false `DNS=false`. however, with this new container if this is env var is passed in at all (or the `-d` switch too I'd assume), it tries to add the up/down scripts here https://github.com/ich777/docker-openvpn-client/blob/master/scripts/start-server.sh#L38
However, it seems in this container those scripts do not (any longer) exist and it causes the container to fail to initiate with a missing file error.

**Comment by ich777** [comment]
~~I will look into this ASAP and report back.~~

**Comment by ich777** [comment]
@absentbri I've updated the container but haven't got time yet to test, please report back if it is working now.

**Comment by brianramseyau** [comment]
@ich777 sorry but I've not had the time to get back to this, I'll see what I can do on the weekend.

**Comment by ich777** [comment]
@absentbri same over here... I really appreciate your help with this.

**Comment by ich777** [comment]
@absentbri I close the issue for now, feel free to open it again or create a new one.
