### ISSUE TITLE
setting up openvpn-client with surfshark

### ISSUE THREAD

**Issue by Kuipermatthijs** [ich777/docker-openvpn-client#6]
Hello, 

First of all, thanks for developing this piece of software. 
I run into an issue while installing the docker with unraid, using the files from surfshark. 

I get the following log file:

2022-11-29 13:30:49 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
2022-11-29 13:30:49 TLS Error: TLS handshake failed
2022-11-29 13:30:49 SIGUSR1[soft,tls-error] received, process restarting
2022-11-29 13:30:49 Restart pause, 5 second(s)
2022-11-29 13:30:54 WARNING: --ping should normally be used with --ping-restart or --ping-exit
2022-11-29 13:30:54 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2022-11-29 13:30:54 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2022-11-29 13:30:54 TCP/UDP: Preserving recently used remote address: [AF_INET]188.166.43.117:1194
2022-11-29 13:30:54 Socket Buffers: R=[212992->212992] S=[212992->212992]
2022-11-29 13:30:54 UDP link local: (not bound)
2022-11-29 13:30:54 UDP link remote: [AF_INET] . .43. :1194
2022-11-29 13:31:54 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
2022-11-29 13:31:54 TLS Error: TLS handshake failed
2022-11-29 13:31:54 SIGUSR1[soft,tls-error] received, process restarting

I have made a vpn.ovpn with the .ovpn provided from surfshark, and a vpn.auth with the client and password. 

the .ovpn file starts with:
  GNU nano 7.0                                                         vpn.conf                                                                   
client
dev tun
proto udp
remote nl-ams-mp001.prod.surfshark.com 1194
resolv-retry infinite
remote-random
nobind
tun-mtu 1500
tun-mtu-extra 32
mssfix 1450
persist-key
persist-tun
ping 15
ping-restart 0
ping-timer-rem
reneg-sec 0

remote-cert-tls server

auth-user-pass

#comp-lzo
verb 3
pull
fast-io
cipher AES-256-CBC

Would you be able to recognize this, or am I just messing things up.

**Comment by Kuipermatthijs** [comment]
![error2](https://user-images.githubusercontent.com/76099662/204657581-3f354b23-1da7-4b88-ac37-2925ede91016.png)

**Comment by ich777** [comment]
> First of all, thanks for developing this piece of software.

I've only forked it and updated it to be compatible with modern ovpn files and certificates.



> Would you be able to recognize this, or am I just messing things up.

I'm not really familiar with surfshark, what files have you put in your openvpn folder? The log tells me that it is not properly configured and the CA is missing.

**Comment by Kuipermatthijs** [comment]
The file i tried to add is

client
dev tun
proto udp
remote nl-ams-mp001.prod.surfshark.com 1194
resolv-retry infinite
remote-random
nobind
tun-mtu 1500
tun-mtu-extra 32
mssfix 1450
persist-key
persist-tun
ping 15
ping-restart 0
ping-timer-rem
reneg-sec 0

remote-cert-tls server

auth-user-pass

#comp-lzo
verb 3
pull
fast-io
cipher AES-256-CBC

auth SHA512

<ca>
-----BEGIN CERTIFICATE-----
MIIFTTCCAzWgAwIBAgIJAMs9S3fqwv+mMA0GCSqGSIb3DQEBCwUAMD0xCzAJBgNV
BAYTAlZHMRIwEAYDVQQKDAlTdXJmc2hhcmsxGjAYBgNVBAMMEVN1cmZzaGFyayBS
b290IENBMB4XDTE4MDMxNDA4NTkyM1oXDTI4MDMxMTA4NTkyM1owPTELMAkGA1UE
BhMCVkcxEjAQBgNVBAoMCVN1cmZzaGFyazEaMBgGA1UEAwwRU3VyZnNoYXJrIFJv
b3QgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDEGMNj0aisM63o
SkmVJyZPaYX7aPsZtzsxo6m6p5Wta3MGASoryRsBuRaH6VVa0fwbI1nw5ubyxkua
Na4v3zHVwuSq6F1p8S811+1YP1av+jqDcMyojH0ujZSHIcb/i5LtaHNXBQ3qN48C
c7sqBnTIIFpmb5HthQ/4pW+a82b1guM5dZHsh7q+LKQDIGmvtMtO1+NEnmj81BAp
FayiaD1ggvwDI4x7o/Y3ksfWSCHnqXGyqzSFLh8QuQrTmWUm84YHGFxoI1/8AKdI
yVoB6BjcaMKtKs/pbctk6vkzmYf0XmGovDKPQF6MwUekchLjB5gSBNnptSQ9kNgn
TLqi0OpSwI6ixX52Ksva6UM8P01ZIhWZ6ua/T/tArgODy5JZMW+pQ1A6L0b7egIe
ghpwKnPRG+5CzgO0J5UE6gv000mqbmC3CbiS8xi2xuNgruAyY2hUOoV9/BuBev8t
tE5ZCsJH3YlG6NtbZ9hPc61GiBSx8NJnX5QHyCnfic/X87eST/amZsZCAOJ5v4EP
SaKrItt+HrEFWZQIq4fJmHJNNbYvWzCE08AL+5/6Z+lxb/Bm3dapx2zdit3x2e+m
iGHekuiE8lQWD0rXD4+T+nDRi3X+kyt8Ex/8qRiUfrisrSHFzVMRungIMGdO9O/z
CINFrb7wahm4PqU2f12Z9TRCOTXciQIDAQABo1AwTjAdBgNVHQ4EFgQUYRpbQwyD
ahLMN3F2ony3+UqOYOgwHwYDVR0jBBgwFoAUYRpbQwyDahLMN3F2ony3+UqOYOgw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAn9zV7F/XVnFNZhHFrt0Z
S1Yqz+qM9CojLmiyblMFh0p7t+Hh+VKVgMwrz0LwDH4UsOosXA28eJPmech6/bjf
ymkoXISy/NUSTFpUChGO9RabGGxJsT4dugOw9MPaIVZffny4qYOc/rXDXDSfF2b+
303lLPI43y9qoe0oyZ1vtk/UKG75FkWfFUogGNbpOkuz+et5Y0aIEiyg0yh6/l5Q
5h8+yom0HZnREHhqieGbkaGKLkyu7zQ4D4tRK/mBhd8nv+09GtPEG+D5LPbabFVx
KjBMP4Vp24WuSUOqcGSsURHevawPVBfgmsxf1UCjelaIwngdh6WfNCRXa5QQPQTK
ubQvkvXONCDdhmdXQccnRX1nJWhPYi0onffvjsWUfztRypsKzX4dvM9k7xnIcGSG
EnCC4RCgt1UiZIj7frcCMssbA6vJ9naM0s7JF7N3VKeHJtqe1OCRHMYnWUZt9vrq
X6IoIHlZCoLlv39wFW9QNxelcAOCVbD+19MZ0ZXt7LitjIqe7yF5WxDQN4xru087
FzQ4Hfj7eH1SNLLyKZkA1eecjmRoi/OoqAt7afSnwtQLtMUc2bQDg6rHt5C0e4dC
LqP/9PGZTSJiwmtRHJ/N5qYWIh9ju83APvLm/AGBTR2pXmj9G3KdVOkpIC7L35dI
623cSEC3Q3UZutsEm/UplsM=
-----END CERTIFICATE-----
</ca>
key-direction 1
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
b02cb1d7c6fee5d4f89b8de72b51a8d0
c7b282631d6fc19be1df6ebae9e2779e
6d9f097058a31c97f57f0c35526a44ae
09a01d1284b50b954d9246725a1ead1f
f224a102ed9ab3da0152a15525643b2e
ee226c37041dc55539d475183b889a10
e18bb94f079a4a49888da566b9978346
0ece01daaf93548beea6c827d9674897
e7279ff1a19cb092659e8c1860fbad0d
b4ad0ad5732f1af4655dbd66214e552f
04ed8fd0104e1d4bf99c249ac229ce16
9d9ba22068c6c0ab742424760911d463
6aafb4b85f0c952a9ce4275bc821391a
a65fcd0d2394f006e3fba0fd34c4bc4a
b260f4b45dec3285875589c97d3087c9
134d3a3aa2f904512e85aa2dc2202498
-----END OpenVPN Static key V1-----
</tls-auth>

It might have a different layout, which causes the issue. 
I do have the confermation that this file would not be changed when in stalled regularly. 
And maybe it is just not compatible.

**Comment by ich777** [comment]
> The file i tried to add is

And how is this file named?
You also need a second file with the username and password which is needed to connect to your VPN provider.

**Comment by Kuipermatthijs** [comment]
it is the vpn.ovpn. 
and I did make a vpn.auth with username and password

**Comment by ich777** [comment]
@Kuipermatthijs I've now tested it with Privado.io and have no issue whatsoever, I'm using this config file:

```
client
dev tun
#dev-node "PrivadoVPN (OpenVPN)"
proto udp
remote **REDACTED** 1194
resolv-retry infinite
nobind
persist-key
persist-tun
persist-remote-ip

verify-x509-name **REDACTED** name

tls-client

#block-outside-dns
route-ipv6 ::/0
route 0.0.0.0 0.0.0.0 vpn_gateway
tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA:TLS-DHE-DSS-WITH-AES-256-CBC-SHA:TLS-RSA-WITH-AES-256-CBC-SHA
remote-cert-tls server
auth-user-pass
verb 3
auth SHA256
data-ciphers AES-256-CBC
data-ciphers-fallback AES-256-CBC
route-delay 3

<ca>
-----BEGIN CERTIFICATE-----
**REDACTED**
-----END CERTIFICATE-----
</ca>
```

I really can't tell what's going on there with Surfshark, seems like an invalid configuration and the handshake failed from what I see in the logs.
Have you changed anything in the template?

**Comment by Kuipermatthijs** [comment]
I did not make changes, it could however be the header that is not recognized. Or in general it might not be working for surfshark at all. 
I'll dive deeper into this at a later moment. Thank you for trying.

**Comment by ich777** [comment]
@Kuipermatthijs maybe try to edit your ovpn file so that it has only the configurations like from Privado.io in it.
BTW you can also try Privado for free if I'm not mistaken, maybe try that to make sure there is nothing else weird going on.

Please let me know about your findings, I will close this issue after a week if I don't hear back from you.

**Comment by ich777** [comment]
@Kuipermatthijs I close the issue for now, feel free to open it again or create a new one.

**Comment by Kuipermatthijs** [comment]
Sorry for the delay. Yeah, you can close it. I will continue to do some investigation, also with surfshark. 
If I have updates, I'll let you know.

**Comment by Kuipermatthijs** [comment]
I did make the privado.io account and that works. 
I am now in contact with surfshark to see if they can help me out. 

Thank you for the suppport, and keeping you updated.
