### ISSUE TITLE
connecting other containers

### ISSUE THREAD

**Issue by Foresaken1** [ich777/docker-openvpn-client#8]
Forgive me but I'm not sure how to connect other containers to this container in unraid. I'm new to unraid and a little new to docker with out portainer.
I assume I'm adding a variable but not to sure where to put the info like --net=container:OpenVPN-Client. I'm sure I'll run into other stuff  I don't know how to do but we'll start here? thanks

**Comment by ich777** [comment]
@Foresaken1 please read the description again, you have to add `--net=container:OpenVPN-Client` (with Advanced View enabled and at the field `Extra Parameters` below `WebUI`) to the container that you want to route through this container and set the network to None.

This question would be better suited in the support thread from the container on the Unraid forums.
I'm closing this issue now, please use the support thread on the Unraid Forums.
